server:
  port: 8083

spring:
  application:
    name: scoring-service
  rabbitmq:
    listener:
      simple:
        missing-queues-fatal: false

management:
  endpoints:
    web:
      exposure:
        include: health, info
